version: '2'
services:
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /srv/docker/influxdb:/var/lib/influxdb
    labels:
      - "traefik.backend=influxdb"
      - "traefik.port=8083" 
      - "traefik.frontend.rule=Host:influxdb.weberhome.lan"
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /srv/docker/grafana:/var/lib/grafana
