version: '2'
services:
  influxdb:
    image: influxdb
    restart: always
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/influxdb/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - /srv/docker/influxdb:/var/lib/influxdb
  grafana:
    image: grafana/grafana
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /srv/docker/grafana/grafana.conf:/etc/grafana/grafana.ini:ro
      - /srv/docker/grafana:/var/lib/grafana